async function loadSavedSettings() {
  const result = await chrome.storage.local.get(["proxyHost", "proxyPort", "proxyScheme"]);
  if (result.proxyHost) document.getElementById("host").value = result.proxyHost;
  if (result.proxyPort) document.getElementById("port").value = result.proxyPort;
  if (result.proxyScheme) document.getElementById("scheme").value = result.proxyScheme;
}

async function saveSettings(host, port, scheme) {
  await chrome.storage.local.set({
    proxyHost: host,
    proxyPort: port,
    proxyScheme: scheme
  });
}

async function updateStatus() {
  const response = await chrome.runtime.sendMessage({ action: "getStatus" });
  const statusDiv = document.getElementById("status");
  if (response.enabled) {
    statusDiv.className = "status status-on";
    statusDiv.innerHTML = "🔥 ACTIVE 🔥";
  } else {
    statusDiv.className = "status status-off";
    statusDiv.innerHTML = "💀 INACTIVE 💀";
  }
}

async function getCurrentTab() {
  const [tab] = await chrome.tabs.query({ active: true, currentWindow: true });
  return tab;
}

async function getCookiesForCurrentSite() {
  const tab = await getCurrentTab();
  if (!tab || !tab.url) return [];
  
  const url = new URL(tab.url);
  const domain = url.hostname;
  
  const allCookies = await chrome.cookies.getAll({});
  
  return allCookies.filter(cookie => {

    const cookieDomain = cookie.domain.replace(/^\./, '');
    return domain.includes(cookieDomain) || cookieDomain.includes(domain);
  });
}

function formatCookieValue(cookie) {
  return `${cookie.name}=${cookie.value}`;
}

function formatCookiesAsJSON(cookies) {
  return JSON.stringify(cookies, null, 2);
}

function formatCookiesAsNetscape(cookies) {
  const lines = [
    "# Netscape HTTP Cookie File",
    "# https://curl.haxx.se/docs/http-cookies.html",
    "# This file was generated by HAD Proxy Extension"
  ];
  
  for (const cookie of cookies) {
    const domain = cookie.domain.startsWith('.') ? cookie.domain : '.' + cookie.domain;
    const includeSubdomains = cookie.domain.startsWith('.') ? 'TRUE' : 'FALSE';
    const path = cookie.path || '/';
    const secure = cookie.secure ? 'TRUE' : 'FALSE';
    const expires = cookie.expirationDate ? Math.floor(cookie.expirationDate) : 0;
    const name = cookie.name;
    const value = cookie.value;
    
    lines.push(`${domain}\t${includeSubdomains}\t${path}\t${secure}\t${expires}\t${name}\t${value}`);
  }
  
  return lines.join('\n');
}

function formatCookiesAsHeaderString(cookies) {
  const cookieStrings = cookies.map(c => `${c.name}=${c.value}`);
  return cookieStrings.join('; ');
}

function parseNetscapeCookieFile(content) {
  const lines = content.split('\n');
  const cookies = [];
  
  for (const line of lines) {
    const trimmed = line.trim();
    if (trimmed === '' || trimmed.startsWith('#')) continue;
    
    const parts = trimmed.split('\t');
    if (parts.length >= 7) {
      const cookie = {
        domain: parts[0].replace(/^\./, ''),
        path: parts[2],
        secure: parts[3] === 'TRUE',
        expirationDate: parseInt(parts[4]) || undefined,
        name: parts[5],
        value: parts[6],
        httpOnly: false,
        sameSite: 'lax'
      };
      cookies.push(cookie);
    }
  }
  
  return cookies;
}

function parseHeaderString(headerString) {
  const cookies = [];
  const pairs = headerString.split(';').map(s => s.trim());
  
  for (const pair of pairs) {
    const equalIndex = pair.indexOf('=');
    if (equalIndex > 0) {
      const name = pair.substring(0, equalIndex);
      const value = pair.substring(equalIndex + 1);
      cookies.push({
        name: name,
        value: value,
        domain: '',
        path: '/',
        secure: false,
        httpOnly: false,
        sameSite: 'lax'
      });
    }
  }
  
  return cookies;
}

async function displayCookies() {
  const cookies = await getCookiesForCurrentSite();
  const cookieListDiv = document.getElementById('cookieList');
  
  if (cookies.length === 0) {
    cookieListDiv.innerHTML = '<div class="info-text" style="text-align: center;">🍪 No cookies found for this site</div>';
    return;
  }
  
  let html = '';
  for (const cookie of cookies) {
    html += `
      <div class="cookie-item">
        <div class="cookie-name">🔑 ${escapeHtml(cookie.name)}</div>
        <div class="cookie-value">📝 ${escapeHtml(cookie.value)}</div>
        <div class="cookie-actions">
          <button class="btn-sm delete-cookie" data-name="${escapeHtml(cookie.name)}" style="background:#1a0000; border:1px solid #660000; color:#992222;">🗑️ DELETE</button>
        </div>
      </div>
    `;
  }
  
  cookieListDiv.innerHTML = html;
  
  document.querySelectorAll('.delete-cookie').forEach(btn => {
    btn.addEventListener('click', async (e) => {
      const cookieName = btn.getAttribute('data-name');
      await deleteCookie(cookieName);
      await displayCookies();
    });
  });
}

function escapeHtml(str) {
  const div = document.createElement('div');
  div.textContent = str;
  return div.innerHTML;
}

async function deleteCookie(cookieName) {
  const tab = await getCurrentTab();
  if (!tab || !tab.url) return;
  
  const url = new URL(tab.url);
  const domain = url.hostname;
  
  const cookies = await chrome.cookies.getAll({ domain });
  
  for (const cookie of cookies) {
    if (cookie.name === cookieName) {
      const cookieUrl = `${url.protocol}//${cookie.domain.replace(/^\./, '')}${cookie.path || '/'}`;
      await chrome.cookies.remove({
        url: cookieUrl,
        name: cookie.name
      });
    }
  }
}

async function copyAllCookies() {
  const cookies = await getCookiesForCurrentSite();
  const format = document.getElementById('exportFormat').value;
  let text = '';
  
  if (format === 'json') {
    text = formatCookiesAsJSON(cookies);
  } else if (format === 'netscape') {
    text = formatCookiesAsNetscape(cookies);
  } else if (format === 'header') {
    text = formatCookiesAsHeaderString(cookies);
  }
  
  await navigator.clipboard.writeText(text);
  showNotification('✅ Cookies copied to clipboard!');
}

async function exportCookies() {
  const cookies = await getCookiesForCurrentSite();
  const format = document.getElementById('exportFormat').value;
  let content = '';
  let filename = '';
  let mimeType = '';
  
  if (format === 'json') {
    content = formatCookiesAsJSON(cookies);
    filename = 'cookies.json';
    mimeType = 'application/json';
  } else if (format === 'netscape') {
    content = formatCookiesAsNetscape(cookies);
    filename = 'cookies.txt';
    mimeType = 'text/plain';
  } else if (format === 'header') {
    content = formatCookiesAsHeaderString(cookies);
    filename = 'cookies_header.txt';
    mimeType = 'text/plain';
  }
  
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
  
  showNotification(`✅ Cookies exported as ${filename}`);
}

async function importCookies() {
  const importData = document.getElementById('importData').value;
  if (!importData.trim()) {
    showNotification('❌ Please paste cookie data to import');
    return;
  }
  
  const tab = await getCurrentTab();
  if (!tab || !tab.url) {
    showNotification('❌ Cannot get current tab');
    return;
  }
  
  const url = new URL(tab.url);
  let cookies = [];
  
  const trimmed = importData.trim();
  if (trimmed.startsWith('{') || trimmed.startsWith('[')) {

    try {
      const parsed = JSON.parse(trimmed);
      cookies = Array.isArray(parsed) ? parsed : [parsed];
    } catch (e) {
      showNotification('❌ Invalid JSON format');
      return;
    }
  } else if (trimmed.includes('\t') && (trimmed.includes('# Netscape') || trimmed.includes('.com\t'))) {

    cookies = parseNetscapeCookieFile(importData);
  } else if (trimmed.includes('=') && !trimmed.includes('{')) {

    cookies = parseHeaderString(importData);
  } else {
    showNotification('❌ Unknown cookie format');
    return;
  }
  
  if (cookies.length === 0) {
    showNotification('❌ No valid cookies found');
    return;
  }
  
  let imported = 0;
  for (const cookie of cookies) {
    if (!cookie.name || !cookie.value) continue;
    
    const cookieDetails = {
      url: url.origin,
      name: cookie.name,
      value: cookie.value,
      path: cookie.path || '/',
      secure: cookie.secure || false,
      httpOnly: cookie.httpOnly || false,
      sameSite: cookie.sameSite || 'lax'
    };
    
    if (cookie.expirationDate) {
      cookieDetails.expirationDate = cookie.expirationDate;
    }
    
    if (cookie.domain && cookie.domain !== url.hostname) {
      cookieDetails.domain = cookie.domain;
    }
    
    try {
      await chrome.cookies.set(cookieDetails);
      imported++;
    } catch (e) {
      console.error('Failed to set cookie:', e);
    }
  }
  
  showNotification(`✅ Imported ${imported} cookies`);
  document.getElementById('importData').value = '';
  await displayCookies();
}

function showNotification(message) {
  const notificationDiv = document.createElement('div');
  notificationDiv.style.cssText = `
    position: fixed;
    bottom: 10px;
    left: 50%;
    transform: translateX(-50%);
    background: #1a0303;
    border: 1px solid #ff0000;
    color: #ff6666;
    padding: 8px 12px;
    border-radius: 6px;
    font-size: 11px;
    z-index: 1000;
    white-space: nowrap;
  `;
  notificationDiv.textContent = message;
  document.body.appendChild(notificationDiv);
  
  setTimeout(() => {
    notificationDiv.remove();
  }, 2000);
}


function setupTabs() {
  const tabs = document.querySelectorAll('.tab-btn');
  const contents = document.querySelectorAll('.tab-content');
  
  tabs.forEach(btn => {
    btn.addEventListener('click', () => {
      const tabName = btn.getAttribute('data-tab');
      
      tabs.forEach(b => b.classList.remove('active'));
      contents.forEach(c => c.classList.remove('active'));
      
      btn.classList.add('active');
      if (tabName === 'proxy') {
        document.getElementById('proxy-tab').classList.add('active');
      } else if (tabName === 'cookies') {
        document.getElementById('cookies-tab').classList.add('active');
        displayCookies();
      }
    });
  });
}

document.getElementById("enableBtn").addEventListener("click", async () => {
  const host = document.getElementById("host").value.trim();
  const port = document.getElementById("port").value;
  const scheme = document.getElementById("scheme").value;
  
  if (!host || !port) {
    alert("[HAD] ERROR: Host & Port required!");
    return;
  }
  
  await saveSettings(host, port, scheme);
  await chrome.runtime.sendMessage({
    action: "setProxy",
    host: host,
    port: port,
    scheme: scheme
  });
  await updateStatus();
});

document.getElementById("disableBtn").addEventListener("click", async () => {
  await chrome.runtime.sendMessage({ action: "disableProxy" });
  await updateStatus();
});


document.getElementById("refreshCookiesBtn").addEventListener("click", async () => {
  await displayCookies();
});

document.getElementById("copyCookiesBtn").addEventListener("click", async () => {
  await copyAllCookies();
});

document.getElementById("exportBtn").addEventListener("click", async () => {
  await exportCookies();
});

document.getElementById("importBtn").addEventListener("click", async () => {
  await importCookies();
});

loadSavedSettings();
updateStatus();
setupTabs();

displayCookies();
